name: Deploy Gradio App to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Hugging Face Remote
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/AshrithaChintha/project

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          set -e
          git push --force space main

